In [123]:
import numpy as np

In [124]:
samples = [np.array([1,2,3]), np.array([4,8,5]), np.array([3,12,9]), np.array([1,8,5]), np.array([5,14,2]), np.array([7,4,1]), np.array([9,8,9]), np.array([3,8,1]), np.array([11,5,6]), np.array([10,11,7])]

In [125]:
samples = [i.reshape(3,1) for i in samples]

In [126]:
samples

[array([[1],
        [2],
        [3]]), array([[4],
        [8],
        [5]]), array([[ 3],
        [12],
        [ 9]]), array([[1],
        [8],
        [5]]), array([[ 5],
        [14],
        [ 2]]), array([[7],
        [4],
        [1]]), array([[9],
        [8],
        [9]]), array([[3],
        [8],
        [1]]), array([[11],
        [ 5],
        [ 6]]), array([[10],
        [11],
        [ 7]])]

In [127]:
samples = np.array(samples)

In [128]:
samples

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 8],
        [ 5]],

       [[ 3],
        [12],
        [ 9]],

       [[ 1],
        [ 8],
        [ 5]],

       [[ 5],
        [14],
        [ 2]],

       [[ 7],
        [ 4],
        [ 1]],

       [[ 9],
        [ 8],
        [ 9]],

       [[ 3],
        [ 8],
        [ 1]],

       [[11],
        [ 5],
        [ 6]],

       [[10],
        [11],
        [ 7]]])

In [129]:
samples_mean = [np.mean(samples[:,i]) for i in range(3)]

In [130]:
samples_mean = np.array(samples_mean).reshape(3,1)

In [131]:
samples_mean

array([[5.4],
       [8. ],
       [4.8]])

In [132]:
covariance = 0
for i in range(10):
    covariance += np.dot(samples[i]-samples_mean,(samples[i]-samples_mean).T)
covariance *= 0.1
covariance

array([[12.04,  0.5 ,  3.28],
       [ 0.5 , 12.2 ,  2.9 ],
       [ 3.28,  2.9 ,  8.16]])

In [133]:
np.linalg.eigvals(covariance)

array([ 5.47203291, 11.63052369, 15.2974434 ])

In [134]:
np.linalg.eig(covariance)

(array([ 5.47203291, 11.63052369, 15.2974434 ]),
 array([[ 0.39985541, -0.67817891, -0.6165947 ],
        [ 0.33758926,  0.73439013, -0.58881629],
        [-0.85214385, -0.02728563, -0.52259579]]))

In [135]:
PCA_list = list(np.linalg.eig(covariance))
PCA_list

[array([ 5.47203291, 11.63052369, 15.2974434 ]),
 array([[ 0.39985541, -0.67817891, -0.6165947 ],
        [ 0.33758926,  0.73439013, -0.58881629],
        [-0.85214385, -0.02728563, -0.52259579]])]

In [136]:
import sympy
from sympy import Matrix
PCA_list2 = [Matrix(i) for i in PCA_list[1].tolist()]
PCA_list2

[Matrix([
 [ 0.399855412733346],
 [-0.678178905920313],
 [-0.616594697084375]]), Matrix([
 [ 0.337589263453302],
 [ 0.734390131950119],
 [-0.588816289937145]]), Matrix([
 [ -0.852143848249169],
 [-0.0272856309990092],
 [ -0.522595786657416]])]

In [137]:
PCA_array=np.array(np.array(sympy.GramSchmidt(PCA_list2, True)).astype('float64'))
PCA_array

array([[ 0.39985541, -0.67817891, -0.6165947 ],
       [ 0.33758926,  0.73439013, -0.58881629],
       [-0.85214385, -0.02728563, -0.52259579]])

In [138]:
record_list = []
for i in range(10):
    PC = np.dot(PCA_array.T,samples[i]-samples_mean)
    record_list.append(PC)
    print(PC)
    print()
    print(samples[i])
    print()
    print('################################################')

[[-2.25104047]
 [-1.37323947]
 [ 7.18658682]]

[[1]
 [2]
 [3]]

################################################
[[-0.73022635]
 [ 0.94399334]
 [ 0.75871342]]

[[4]
 [8]
 [5]]

################################################
[[-3.1883001 ]
 [ 4.45059025]
 [-3.07034019]]

[[ 3]
 [12]
 [ 9]]

################################################
[[-1.92979259]
 [ 2.97853006]
 [ 2.60849751]]

[[1]
 [8]
 [5]]

################################################
[[ 4.25159619]
 [ 4.75401212]
 [-1.82299166]]

[[ 5]
 [14]
 [ 2]]

################################################
[[ 2.52755823]
 [-3.91896138]
 [ 3.35457763]]

[[7]
 [4]
 [1]]

################################################
[[-2.13952468]
 [-2.55604371]
 [-4.41464321]]

[[9]
 [8]
 [9]]

################################################
[[2.27849363]
 [1.73131477]
 [3.46569126]]

[[3]
 [8]
 [1]]

################################################
[[ 0.2038499 ]
 [-6.03371503]
 [-2.31359638]]

[[11]
 [ 5]
 [ 6]]

##########################

In [140]:
record_list

[array([[-2.25104047],
        [-1.37323947],
        [ 7.18658682]]), array([[-0.73022635],
        [ 0.94399334],
        [ 0.75871342]]), array([[-3.1883001 ],
        [ 4.45059025],
        [-3.07034019]]), array([[-1.92979259],
        [ 2.97853006],
        [ 2.60849751]]), array([[ 4.25159619],
        [ 4.75401212],
        [-1.82299166]]), array([[ 2.52755823],
        [-3.91896138],
        [ 3.35457763]]), array([[-2.13952468],
        [-2.55604371],
        [-4.41464321]]), array([[2.27849363],
        [1.73131477],
        [3.46569126]]), array([[ 0.2038499 ],
        [-6.03371503],
        [-2.31359638]]), array([[ 0.97738622],
        [-0.97648096],
        [-5.75249521]])]

In [146]:
record_list2 = []
for i in range(10):
    reconstruct = np.dot(new_PCA_array,record_list[i])+samples_mean
    record_list.append(reconstruct)
    reconstruction_error_sqr = np.dot((reconstruct-samples[i]).T, reconstruct-samples[i])
    print(reconstruct)
    print()
    print(record_list[i])
    print()
    print("reconstruction error:%f"%reconstruction_error_sqr**0.5)
    print('################################################')

[[1.90009072]
 [2.75992709]
 [1.08178971]]

[[-2.25104047]
 [-1.37323947]
 [ 7.18658682]]

reconstruction error:2.251040
################################################
[[4.29198496]
 [8.24651657]
 [4.37774211]]

[[-0.73022635]
 [ 0.94399334]
 [ 0.75871342]]

reconstruction error:0.730226
################################################
[[ 4.27485905]
 [13.07633588]
 [ 6.28310968]]

[[-3.1883001 ]
 [ 4.45059025]
 [-3.07034019]]

reconstruction error:3.188300
################################################
[[1.77163801]
 [8.65147726]
 [3.35553912]]

[[-1.92979259]
 [ 2.97853006]
 [ 2.60849751]]

reconstruction error:1.929793
################################################
[[ 3.29997625]
 [12.56470677]
 [ 5.62297154]]

[[ 4.25159619]
 [ 4.75401212]
 [-1.82299166]]

reconstruction error:4.251596
################################################
[[5.98934216]
 [3.14672348]
 [3.1538432 ]]

[[ 2.52755823]
 [-3.91896138]
 [ 3.35457763]]

reconstruction error:2.527558
#######################